wagtailsharing/tests/settings.py
wagtailsharing/tests/test_views.py

This PR adds a few additional tests to clarify how `WAGTAILSHARING_HOSTNAME` is supposed to work, specifically verifying that adding the sharing hostname as additional Wagtail Site is not required.
- New tests under `wagtailsharing.tests.test_views`.
- `tox`

Additional tests for WAGTAILSHARING_HOSTNAME

---

.travis.yml
README.md
tox.ini

This PR adds [Wagtail 1.9](http://docs.wagtail.io/en/latest/releases/1.9.html) to the list of tested versions.
- Wagtail 1.9 added to the set of tox and Travis environments.
- `tox`

Add testing against Wagtail 1.9

---

CHANGELOG.md
wagtailsharing/wagtail_hooks.py

This PR modifies the sharing link help text in the Wagtail admin menu dropdown from 
> Share latest revision of 'title'
to
> View shared revision of 'title'
to be more consistent with the link text of "View sharing text".
It also updates the CHANGELOG in preparation for v0.3 release.

Improve sharing link text in Wagtail admin menu dropdown

---

CHANGELOG.md
README.rst
wagtailsharing/tests/test_views.py
wagtailsharing/views.py

The current implementation works by using `View.get` but this breaks any non-`GET` HTTP requests, for example if a `Page` type supports some kind of `post` functionality.
This PR changes the way that `wagtailsharing.views.ServeView` works by overriding `View.dispatch` instead of `View.get` and deferring to the built-in Wagtail view functionality for any non-`GET` requests.
- Implement sharing logic via `View.dispatch` instead of `View.get`.
- Thanks to @higs4281 and @virginiacc for identifying this issue.

Properly limit sharing logic to HTTP GET requests

---

CHANGELOG.md
wagtailsharing/tests/test_views.py
wagtailsharing/views.py

The use of BeautifulSoup HTML parsing and re-rendering to insert the preview banner can cause some issues with links in the page. This PR uses a simpler regex match for the body tag and string insertion to add the banner HTML to the top of the page.
It also removes a (hidden) dependence on BeautifulSoup from this package.
- Simpler logic for banner insertion using regex vs BeautifulSoup.
- Thanks to @Scotchester for assistance with this fix.

Use simpler method to insert preview banner

---

.travis.yml
setup.py
tox.ini

Wagtail 1.10 is in the build matrix, and we have been successfully running the combination on cfgov-refresh.

Update wagtail dependency

---

.travis.yml
README.rst
tox.ini
wagtailsharing/tests/test_views.py

This PR modifies the Travis CI testing matrix to add testing against Django 1.11 and Wagtail 1.13. It removes some other test combinations so that the new matrix looks like this:
- Python 2.7, Django 1.8, Wagtail 1.8
- Python 2.7, Django 1.8, Wagtail 1.13
- Python 2.7, Django 1.11, Wagtail 1.13
- Python 3.5, Django 1.11, Wagtail 1.13
- Python 3.6, Django 1.11, Wagtail 1.13
This maintains testing against the Django LTS 1.8 release as well as the Wagtail 1.8 LTS release, and adds testing against the most recent versions of both libraries.

Add testing for Django 1.11 and Wagtail 1.13

---

README.rst
wagtailsharing/tests/test_views.py
wagtailsharing/tests/test_wagtail_hooks.py
wagtailsharing/views.py
wagtailsharing/wagtail_hooks.py

This commit adds two new hooks to this project that allow for customization of the response when a shared page is served.
`before_serve_shared_page` and `after_serve_shared_page` now give users the ability to customize the serving of a shared page revision by adding hooks before and after the `Page.serve()` call. See the changes to [`README.rst`](https://github.com/chosak/wagtail-sharing/blob/custom-serve-logic/README.rst#hooks) for examples.
The sharing banner functionality has been modified to make use of these new hooks in what is hopefully a nicer approach that's more in line with Wagtail conventions.
This PR should address #18 (Support custom logic for shared pages). @tomdyson do you think this will meet the needs of your use case?
- New `before_serve_shared_page` and …

Add additional hooks to support custom serve logic

---

setup.py
tox.ini

This change fixes two minor issues with Django dependencies:
First, it properly adds the "Framework :: Django :: 1.11" trove classifier to setup.py, for proper classification on PyPI.
Second, it adds a maximum version requirement for djangorestframework when testing against Django 1.8 in tox. This is necessary because DRF 3.7 removed support for Django 1.8/1.9. See https://github.com/wagtail/wagtail/pull/3912.

Fix minor issues with Django dependencies

---

CHANGELOG.md
README.rst
setup.py
tox.ini
wagtailsharing/helpers.py
wagtailsharing/models.py
wagtailsharing/tests/settings.py
wagtailsharing/tests/test_helpers.py
wagtailsharing/tests/test_models.py
wagtailsharing/tests/test_urls.py
wagtailsharing/tests/test_views.py
wagtailsharing/tests/urls.py
wagtailsharing/urls.py
wagtailsharing/views.py
wagtailsharing/wagtail_hooks.py

This change adds support for Django 2.0 and Wagtail 2.0 to this package. The README has been updated to reflect the change, and example import syntax has been changed to use Wagtail 2 imports.
Throughout the code, a try/except pattern has been used to support both Wagtail 2.x and legacy 1.x import styles.
Fixes #22.

Adds Django 2.0 and Wagtail 2.0 support

---

wagtailsharing/tests/helpers.py
wagtailsharing/tests/settings.py
wagtailsharing/tests/test_views.py
wagtailsharing/views.py

This change adds logic to support pages that inherit from Wagtail's RoutablePageMixin, as documented [here](https://docs.wagtail.io/en/latest/reference/contrib/routablepage.html).
Currently, subpages of routable pages cannot be previewed if the page has never been published. This corrects that, allowing pages that inherit from `RoutablePageMixin` to be previewed on sharing sites.
See the added tests for examples of how this can be used.
Fixes #27.

Add support for RoutablePageMixin

---

.travis.yml
README.rst
setup.py
tox.ini
wagtailsharing/tests/settings.py

Support production version of Python 3.6 and latest version of Python 3.8
Support production version of Wagtail 1.11 and latest version of Wagtail 2.8
Remove Python 2.7 and 3.5, add Python 3.8:
* README.rst
* setup.py
* tox.ini
* travis.yml
Add support for Wagtail 2.8 to `tox.ini`, `setup.py`, and `travis.yml`
Testing
$ tox
```
...
flake8: commands succeeded
py36-dj111-wag113: commands succeeded
py36-dj111-wag23: commands succeeded
py36-dj20-wag23: commands succeeded
py36-dj22-wag23: commands succeeded
py36-dj22-wag28: commands succeeded
py38-dj22-wag28: commands succeeded
congratulations :)
```

Support Wagtail 2.3

---

.travis.yml
CONTRIBUTING.md
README.rst
pyproject.toml
setup.py
tox.ini
wagtailsharing/__init__.py
wagtailsharing/apps.py
wagtailsharing/checks.py
wagtailsharing/helpers.py
wagtailsharing/migrations/0001_initial.py
wagtailsharing/models.py
wagtailsharing/tests/helpers.py
wagtailsharing/tests/settings.py
wagtailsharing/tests/test_checks.py
wagtailsharing/tests/test_helpers.py
wagtailsharing/tests/test_models.py
wagtailsharing/tests/test_urls.py
wagtailsharing/tests/test_views.py
wagtailsharing/tests/test_wagtail_hooks.py
wagtailsharing/tests/urls.py
wagtailsharing/urls.py
wagtailsharing/views.py
wagtailsharing/wagtail_hooks.py

Support for Django 2.2 imports
Add black to tox
Support for Wagtail 1.13 in tox and travis
`from __future__ import absolute_import, unicode_literals`

Remove Wagtail 1.13 support, add Django 2.2 import support, and add Black for autoformatting

---

wagtailsharing/views.py

Currently if an exception happens when a page is served, error messages can look like this:
```
Traceback (most recent call last):
sharing_site = SharingSite.find_for_request(request)
...
self.model._meta.object_name
wagtailsharing.models.DoesNotExist: SharingSite matching query does not exist.
During handling of the above exception, another exception occurred:
... (actual exception)
```
In this case, wagtail-sharing has nothing to do with the error, but the stack trace includes it because of the way the ServeView logic works.
This commit alters the logic so that the regular view's errors aren't raised from within wagtail-sharing's exception handline. This should improve error messages by removing mention of SharingSite.

Improve error messages by refactoring ServeView

---

.travis.yml
README.rst
setup.py
tox.ini
wagtailsharing/models.py

We should probably only pin Wagtail in this application, and support
the version range for Django that our Wagtail version specifies.

Remove the Django requirement from this application

---

.github/workflows/release.yml

This commit adds our standard GitHub Action to upload releases to PyPI when the release is created in GitHub. This will remove the separate steps of building a wheel and sdist on the tag and uploading it manually when we create a release.
It will require the `TWINE_USERNAME` and `TWINE_PASSWORD` secrets to be created on this repository with the CFPB PyPI credentials. I am happy to do that.
This particular action is already in use in [Django Flags](https://github.com/cfpb/django-flags/blob/master/.github/workflows/release.yml), [Wagtail Flags](https://github.com/cfpb/wagtail-flags/blob/master/.github/workflows/release.yml), and [Wagtail TreeModelAdmin](https://github.com/cfpb/wagtail-treemodeladmin/blob/master/.github/workflows/release.yml).

Add a GitHub Action to upload releases to PyPI

---

.travis.yml
README.rst
setup.py
tox.ini
wagtailsharing/tests/settings.py
wagtailsharing/tests/test_views.py

This task is to pin tox environment on Wagtail 2.10 and ensure all tests pass.
There do not appear to be any upgrade considerations that we should be particularly concerned about with 2.10.
- wagtail 2.10 in tox.ini

Add support for latest Wagtail 2.10 release

---

setup.py

Update version in `setup.py` to provide Wagtail 2.10 support

Release version 2.2.1 to support Wagtail 2.10

---

README.rst

Swaps the Travis CI Build Badge for the Github Actions Badge
- Travis Build Badge to Github Actions Badge

Swap Travis Badge for Github Action Badge

---

wagtailsharing/tests/test_wagtail_hooks.py
wagtailsharing/wagtail_hooks.py

If the HTML `<body>` tag includes newlines before the closing `>`, the sharing banner regular expression would not match it. This fixes that by adding the `re.DOTALL` flag inline.

Add DOTALL flag to sharing banner body-RE

---

README.rst
wagtailsharing/wagtail_hooks.py

As of version 2.10, certain Wagtail hooks now [accept an optional next_url keyword argument](https://docs.wagtail.io/en/stable/releases/2.10.html#new-next-url-keyword-argument-on-register-page-listing-buttons-and-register-page-listing-more-buttons-hooks). This includes the [`register_page_listing_more_buttons`](https://docs.wagtail.io/en/stable/reference/hooks.html#register-page-listing-more-buttons) hook used in this project.
Users of Wagtail 2.10 and 2.11 currently see this deprecation warning:
> RemovedInWagtail212Warning: register_page_listing_more_buttons hooks will require an additional kwarg `next_url` in a future release. Please update your hook function to accept `next_url`.
This commit fixes that warning while still maintaining compatibility with the older versions of Wagtail.

Handle hook signature change in Wagtail 2.10+

---

.github/workflows/test.yml
tox.ini

This change updates our tests to run against Python 3.9.

Update tests to Python 3.9

---

.github/workflows/test.yml
README.rst
tox.ini

This change removes Coveralls in favor of using [diff-cover](https://pypi.org/project/diff-cover/) in GitHub Actions.
This is how we’re doing code coverage in [consumerfinance.gov](https://github.com/cfpb/consumerfinance.gov), [django-flags](https://github.com/cfpb/django-flags), and [wagtail-flags](https://github.com/cfpb/wagtail-flags).

Remove Coveralls

---

.flake8
setup.cfg
tox.ini

"tox -e lint" was failing on this repository. There were multiple conflicting configurations for flake8: in .flake8, tox, and setup.cfg.
This commit simplifies so that the configuration only lives in .flake8, and works again even on the latest version of flake8.
See also https://github.com/cfpb/wagtail-inventory/pull/61.

Fix flake8 configuration

---

wagtailsharing/__init__.py

Django 3.2 removed the need to define a `default_app_config` in an app's \_\_init__.py file:
https://docs.djangoproject.com/en/4.1/releases/3.2/#automatic-appconfig-discovery
This is deprecated as of 3.2 and defining it triggers this warning:
> RemovedInDjango41Warning: 'wagtailsharing' defines default_app_config = 'wagtailsharing.apps.WagtailSharingAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
This commit removes the `default_app_config` definition to remove that deprecation warning.

Remove definition of default_app_config

---

wagtailsharing/wagtail_hooks.py

Wagtail 4 has moved the page header buttons into a drop-down menu, allowing more space for new buttons.
This change adds the “View sharing link” for any page to its header buttons menu, which appear on both the page’s listing view of child pages as well as its edit view.
This means that for every page, the “View sharing link” now appears in the “More” context menu in the parent’s listing view, in the header menu in its own listing view, and in the header menu in its edit view.
Short description explaining the high-level reason for the pull request

Add Sharing Link button to the page header

---

wagtailsharing/tests/test_wagtail_hooks.py
wagtailsharing/wagtail_hooks.py

Wagtail 5.2 [changes](https://docs.wagtail.org/en/latest/releases/5.2.html#hooks-for-page-listing-and-page-header-buttons-no-longer-accept-a-page-perms-argument) the signature of the `register_page_header_buttons` and `register_page_listing_more_buttons` hooks, causing a deprecation warning. This commit alters the hook function signature to comply with both the old and new hook specifications.
Fixes #72.

Fix deprecation warning in Wagtail 5.2
